version: "3"
services:
  airflow:
    build:
        context: .
        dockerfile: app/Dockerfile
    restart: always
    ports:
     - "5000:5000"
     - "8080:8080"
    volumes:
        - ./app:/build

